name: SimpleSoaker
author: 'Boyan Soubachov'
description: 'Blocks deployments if the required soak time has not been reached'
inputs:
    branch:
        description: 'The branch name to monitor & guard'
        required: false
        default: 'master'
    soakPeriod:
        description: 'The soaking period for the last deployment (in seconds)'
        required: true
branding:
    icon: 'droplet'
    color: 'blue'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.branch }}
        - ${{ inputs.soakPeriod }}
